"""add review workflow

Revision ID: 6e37c373ffe1
Revises: c6819117d1b4
Create Date: 2026-10-05 20:17:47.121102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e37c373ffe1'
down_revision: Union[str, None] = 'c6819117d1b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Older development builds called metadata.create_all() at API startup. If
    # those builds already materialized these exact tables, adopt them instead
    # of failing the migration. New databases still follow the normal path.
    existing_tables = set(sa.inspect(op.get_bind()).get_table_names())
    if 'review_items' not in existing_tables:
        op.create_table(
            'review_items',
            sa.Column('id', sa.String(length=36), nullable=False),
            sa.Column('dedupe_key', sa.String(length=255), nullable=False),
            sa.Column('video_id', sa.String(length=36), nullable=False),
            sa.Column('frame_id', sa.String(length=36), nullable=False),
            sa.Column('model_run_id', sa.String(length=36), nullable=False),
            sa.Column('prediction_id', sa.String(length=36), nullable=True),
            sa.Column('reason', sa.String(length=100), nullable=False),
            sa.Column('severity', sa.String(length=20), nullable=False),
            sa.Column('status', sa.String(length=30), nullable=False),
            sa.Column('score', sa.Float(), nullable=True),
            sa.Column('details', sa.JSON(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('resolved_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['frame_id'], ['frames.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(
                ['prediction_id'], ['model_predictions.id'], ondelete='CASCADE'
            ),
            sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('dedupe_key'),
        )
        with op.batch_alter_table('review_items', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_review_items_frame_id'), ['frame_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_review_items_model_run_id'), ['model_run_id'], unique=False)
            batch_op.create_index(
                batch_op.f('ix_review_items_prediction_id'), ['prediction_id'], unique=False
            )
            batch_op.create_index(batch_op.f('ix_review_items_reason'), ['reason'], unique=False)
            batch_op.create_index(batch_op.f('ix_review_items_severity'), ['severity'], unique=False)
            batch_op.create_index(batch_op.f('ix_review_items_status'), ['status'], unique=False)
            batch_op.create_index(batch_op.f('ix_review_items_video_id'), ['video_id'], unique=False)

    if 'review_events' not in existing_tables:
        op.create_table(
            'review_events',
            sa.Column('id', sa.String(length=36), nullable=False),
            sa.Column('review_item_id', sa.String(length=36), nullable=False),
            sa.Column('action', sa.String(length=50), nullable=False),
            sa.Column('reviewer', sa.String(length=255), nullable=True),
            sa.Column('note', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(
                ['review_item_id'], ['review_items.id'], ondelete='CASCADE'
            ),
            sa.PrimaryKeyConstraint('id'),
        )
        with op.batch_alter_table('review_events', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_review_events_action'), ['action'], unique=False)
            batch_op.create_index(
                batch_op.f('ix_review_events_review_item_id'), ['review_item_id'], unique=False
            )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_events_review_item_id'))
        batch_op.drop_index(batch_op.f('ix_review_events_action'))

    op.drop_table('review_events')
    with op.batch_alter_table('review_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_items_video_id'))
        batch_op.drop_index(batch_op.f('ix_review_items_status'))
        batch_op.drop_index(batch_op.f('ix_review_items_severity'))
        batch_op.drop_index(batch_op.f('ix_review_items_reason'))
        batch_op.drop_index(batch_op.f('ix_review_items_prediction_id'))
        batch_op.drop_index(batch_op.f('ix_review_items_model_run_id'))
        batch_op.drop_index(batch_op.f('ix_review_items_frame_id'))

    op.drop_table('review_items')
    # ### end Alembic commands ###
