"""initial media and inference schema

Revision ID: c6819117d1b4
Revises: 
Create Date: 2026-10-05 10:38:23.130382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6819117d1b4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('codec', sa.String(length=100), nullable=True),
    sa.Column('source_frame_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_path')
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videos_status'), ['status'], unique=False)

    op.create_table('annotation_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('annotation_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotation_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_tasks_video_id'), ['video_id'], unique=False)

    op.create_table('frames',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=False),
    sa.Column('timestamp_ms', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_path'),
    sa.UniqueConstraint('video_id', 'frame_number')
    )
    with op.batch_alter_table('frames', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_frames_video_id'), ['video_id'], unique=False)

    op.create_table('model_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('model_kind', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('device', sa.String(length=50), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_frames', sa.Integer(), nullable=False),
    sa.Column('processed_frames', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_runs_model_kind'), ['model_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_runs_video_id'), ['video_id'], unique=False)

    op.create_table('annotation_activity',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('frame_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('annotation_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['frame_id'], ['frames.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['annotation_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('annotation_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotation_activity_frame_id'), ['frame_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_activity_task_id'), ['task_id'], unique=False)

    op.create_table('model_predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_run_id', sa.String(length=36), nullable=False),
    sa.Column('frame_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('annotation_type', sa.String(length=50), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['frame_id'], ['frames.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_predictions_frame_id'), ['frame_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_predictions_label'), ['label'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_predictions_model_run_id'), ['model_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_predictions_status'), ['status'], unique=False)

    op.create_table('processing_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('model_run_id', sa.String(length=36), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processing_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_model_run_id'), ['model_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_video_id'), ['video_id'], unique=False)

    op.create_table('annotations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('frame_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('annotation_type', sa.String(length=50), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('model_prediction_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['frame_id'], ['frames.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_prediction_id'], ['model_predictions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['annotation_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotations_frame_id'), ['frame_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotations_model_prediction_id'), ['model_prediction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotations_task_id'), ['task_id'], unique=False)

    op.create_table('prediction_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prediction_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('annotation_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['annotation_id'], ['annotations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prediction_id'], ['model_predictions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['annotation_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prediction_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prediction_decisions_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_decisions_prediction_id'), ['prediction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_decisions_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prediction_decisions_task_id'))
        batch_op.drop_index(batch_op.f('ix_prediction_decisions_prediction_id'))
        batch_op.drop_index(batch_op.f('ix_prediction_decisions_action'))

    op.drop_table('prediction_decisions')
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotations_task_id'))
        batch_op.drop_index(batch_op.f('ix_annotations_model_prediction_id'))
        batch_op.drop_index(batch_op.f('ix_annotations_frame_id'))

    op.drop_table('annotations')
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processing_jobs_video_id'))
        batch_op.drop_index(batch_op.f('ix_processing_jobs_state'))
        batch_op.drop_index(batch_op.f('ix_processing_jobs_model_run_id'))
        batch_op.drop_index(batch_op.f('ix_processing_jobs_job_type'))

    op.drop_table('processing_jobs')
    with op.batch_alter_table('model_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_predictions_status'))
        batch_op.drop_index(batch_op.f('ix_model_predictions_model_run_id'))
        batch_op.drop_index(batch_op.f('ix_model_predictions_label'))
        batch_op.drop_index(batch_op.f('ix_model_predictions_frame_id'))

    op.drop_table('model_predictions')
    with op.batch_alter_table('annotation_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotation_activity_task_id'))
        batch_op.drop_index(batch_op.f('ix_annotation_activity_frame_id'))

    op.drop_table('annotation_activity')
    with op.batch_alter_table('model_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_runs_video_id'))
        batch_op.drop_index(batch_op.f('ix_model_runs_status'))
        batch_op.drop_index(batch_op.f('ix_model_runs_model_kind'))

    op.drop_table('model_runs')
    with op.batch_alter_table('frames', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_frames_video_id'))

    op.drop_table('frames')
    with op.batch_alter_table('annotation_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotation_tasks_video_id'))
        batch_op.drop_index(batch_op.f('ix_annotation_tasks_status'))

    op.drop_table('annotation_tasks')
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_status'))

    op.drop_table('videos')
    # ### end Alembic commands ###
